### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by tasos14**
updated readme with the new transformer syntax

### CODE REVIEW

**Comment by tasos14** [comment]
I saw your comment on the issue after pushing this changes.
Sorry for the rushed action !

**Comment by hilkeheremans** [comment]
Not a problem at all, especially not if it's rushed action that saves me some time 💯 

Will merge over the next few days

**Comment by aaronisme** [comment]
please merge this readme change to align with the code change, since it change the object type of seamlessImmutableTransformer, before it is an object and after the code change it changed to an function. which seems like a big change.

**Comment by hilkeheremans** [comment]
@aaronisme Yes, you're right. I missed that in the rush, and that is in fact a breaking change. I should have bumped to 2.x for that. I'll try to take care of it in a few hours. Thanks for letting me know.

**Comment by aaronisme** [comment]
@hilkeheremans cool, thanks for this library, it really helps a lot. meanwhile, I think the original `seamlessImmutableTransformer` may not seams a proper name after this change. so I make a PR to change the name to `seamlessImmutableTransformCreator`.

**Pull request merged**
